on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run test:coverage
      - uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: ./coverage/lcov.info
          artifact-name: code-coverage-report
          github-token: ${{ secrets.TOKEN }}
      - uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          github-token: ${{ secrets.TOKEN }}
          lcov-file: ./coverage/lcov.info
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          path: build
